package bedalton.creatures.breed.render.cli

const val RENDER_ERROR_CODE__MISSING_REQUIRED_AGE_OR_GENDER = 1000
const val RENDER_ERROR_CODE__MISSING_REQUIRED_BREED_VALUES = 1001
const val RENDER_ERROR_CODE__FAILED_TO_RENDER = 1002
const val RENDER_ERROR_CODE__FAILED_TO_WRITE_IMAGE = 1003
const val RENDER_ERROR_CODE__INVALID_GENDER_VALUE = 1004
const val RENDER_ERROR_CODE__INVALID_AGE_VALUE = 1005
const val RENDER_ERROR_CODE__INVALID_GENUS = 1006
const val RENDER_ERROR_CODE__INVALID_BREED = 1007
const val RENDER_ERROR_CODE__MISSING_POSE = 1008
const val RENDER_ERROR_CODE__INVALID_POSE_STRING = 1009
const val RENDER_ERROR_CODE__INVALID_TINT_VALUE = 1010
const val RENDER_ERROR_CODE__MISSING_OUTPUT_FILE = 1011
